config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :tasks, only: %i[index create] do
    member do
      get 'complete'
    end
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
   validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   def index
      
   end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
   layout false
   def index
      @tasks = Task.order('created_at DESC') # instance variable: @tasks, available in the view "tasks#index"
      @task = Task.new # for the form

      @task_all = Task.count
      @task_completed = get_completed

      respond_to do |format|
         format.html # <- to render the HTML !!
         format.json { # <- to render the json from fetch
            render json: { task_completed: get_completed } 
         }
    end
   end

   def create
      @task = Task.create(task_params) # get the form_data with
      @task.save
      # return unless @task.save
      
      redirect_to tasks_path unless @task.save
      ActionCable.server.broadcast('tasks_channel', {})
   end

   def complete
      @task = Task.find(params[:id])
      @task.update(completed: true)
      ActionCable.server.broadcast('tasks_channel', {})
   end
  
   private
   def task_params
      params.require(:task).permit(:title)
   end


   def get_completed
      Task.where({completed: true}).count
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div 
   data-controller="tasks"
   data-tasks-url-value="<%= tasks_path %>"
   data-tasks-target='listing'>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoStim</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task, remote: true, data: { action: 'ajax:success->tasks#load'}) do |f| %>
   <%= f.text_field :title %>
   <%= f.submit "Add" %>
<% end %>

app/views/tasks/_task.html.erb
<li>  
      <% if task.completed %>
         <s><%= task.title %></s>
      <% else %>
         <%= task.title %> - <%= link_to('Complete', complete_task_path(task), remote: true, data: { action: 'ajax:success->tasks#load'}) %>
      <% end %>

   </li>

app/views/tasks/index.html.erb
<div data-controller="counter">
<h4>Query count nb of Tasks: <%= @task_all  %></h4>
<h4>Query count nb complet tasks: <%= @task_completed  %></h4>
<button data-action="click->counter#refresh">
Fetch() completed tasks: <span data-counter-target="count"></span>
</button>

</div>
<div>
   <h3>Enter new task:</h3>
   <%= render 'tasks/form', task: @task %>
</div>
<h2>Tasks list</h2>
<p>rendered by iterating partials</p>
<ul>
    <%= render(partial: 'tasks/task', collection: @tasks) %>

    <!-- below is equivalent output but BAD since it calls n times a partial:
   -->
   <h2>Again</h2>
   <% @tasks.each do |task| %>
      <%= render 'tasks/task', task: task %>
   <% end %>
   
</ul>